server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/pokesync
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: pokesync-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cache:
    type: redis
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 60000

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} # 1 hora en milisegundos

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
