server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pokesync
  kafka:
    bootstrap-servers: localhost:9092
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} # 1 hora en milisegundos

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
